kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-for-pods
spec:
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 3Gi
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  nfs:
    server: nfs-server
    path: /data
    readOnly: no
